### ISSUE TITLE
Sword + shield unequip don't work

### ISSUE THREAD

**Issue by SimonTheLiver** [SovnSkyrim/QWEST#13]
I was trying on my own to find mod responsible for getting shield on back in QWEST! or similar for it and find a fix but can't figure it out. The issue I have is that NPC with shield and sword equppied do not shelter these. First I saw it with Inigo, when he got only sword is fine but when I give him a shield after a fight he is still walking with shield and sword out. I started a new game and I saw the same issue with the NPC from the start (forget his name). The guy from empire who helps you. To be clear I do not mess with confuguration of mods only the steps which are in setup options. 
In advance thanks for any help.

**Comment by SovnSkyrim** [comment]
NPCs treated as followers will unsheath their weapons when you unsheath them too.
If they bug out and don't, generally sneaking or making them wait solves the issues.
The mod responsible for shields on back is AllGUD in MCMs.
If you need more help go in the Discord.
