### ISSUE TITLE
Update pack to copy Skyrim install so base files aren't affected.

### ISSUE THREAD

**Issue by yonderbeard** [SovnSkyrim/QWEST#19]
Currently it appears that this pack is installed on the base Skyrim install location. This creates an issue if you want to have multiple packs installed simultaneously. Other similar packs make a copy of the core game files in a "Stock Game" folder and act on those, see Serenity II for an example.

If possible could this pack be updated to behave similarly so it doesn't affect the core game files of the Skyrim install.

**Comment by Althro** [comment]
This will be addressed in the 4.0 update alongside many other things. Thank you for recommending this.
