### ISSUE TITLE
How can i remove Common clothes and the mod armor variants... because i dont like these 

### ISSUE THREAD

**Issue by SHIIIZA117** [SovnSkyrim/QWEST#22]
the list is Ultra great but i dont like these additional clothes and armors.. and they seem hardwired into the List with many dependencies

at best i would like to remove the whole skyrim outfitted mods

**Comment by SovnSkyrim** [comment]
You cant, modifications (outside of the ones the readme covers) aren't supported.
This isn't the place for support; refer to the discords.
Asking for support on modifications breaks the rules of the discords.
