### ISSUE TITLE
No "A Matter of Time"

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [SovnSkyrim/QWEST#5]
Just curious since it is a must have imo and was listed in the docs.

**Comment by SovnSkyrim** [comment]
true could have it, i didnt feel like it was a must for a quest list since time isn't like, ultra important but why not

**Comment by EzioTheDeadPoet** [comment]
I saw it as a list that has basically everything the big boys have, besides the graphics that nuke peoples systems. And a lot of stuff especially in the character creation options made it feel that way.

**Comment by SovnSkyrim** [comment]
added
