### ISSUE TITLE
Custom overwrite folder for SKSE

### ISSUE THREAD

**Issue by EzioTheDeadPoet** [SovnSkyrim/QWEST#8]
So people wont get a red triangle for files or presets they saved, just mention it in the README so they can backup their presets before updates.

**Comment by SovnSkyrim** [comment]
dont even know how to do that, i just dont care about the red triangle and most SE lists dont care neither but it can be a cool idea i guess, if i knew how to.

**Comment by SovnSkyrim** [comment]
done
